import { describe, expect, it } from "vitest";

import { createSeededProblem } from "./problems";
import type { TutorTurn } from "./types";
import {
  GUIDANCE_REVEAL_ORDER,
  HELP_REVEAL_DELAY_MS,
  changedEquationParts,
  guidanceRevealDelayMs,
  problemUpdateAnnouncement,
  tutorGuidanceText,
  tutorSourceExplanation,
  tutorSourceLabel,
  tutorUpdateAnnouncement,
} from "./presentation";

const tutorTurn: TutorTurn = {
  stage: "diagnosis",
  misconception: "arithmetic_error",
  diagnosis: "The distributed constant changed value.",
  feedback: "Keep both sides balanced.",
  nextPrompt: "What would you add to both sides?",
  intervention: "socratic_question",
  hintLevel: 1,
  isCorrect: false,
  revealAnswer: false,
};

describe("presentation transitions", () => {
  it("orders guidance from the learner turn through evidence", () => {
    expect(GUIDANCE_REVEAL_ORDER).toEqual([
      "learner",
      "diagnosis",
      "feedback",
      "nextPrompt",
      "evidence",
    ]);

    const delays = GUIDANCE_REVEAL_ORDER.map(guidanceRevealDelayMs);
    expect(delays).toEqual([0, 100, 260, 420, 560]);
    expect(delays).toEqual([...delays].sort((left, right) => left - right));
    expect(HELP_REVEAL_DELAY_MS).toBe(8_000);
  });

  it("marks only visible equation parameters that changed", () => {
    const distribution = createSeededProblem(42, 4);
    const changedDistribution = createSeededProblem(43, 4);

    expect(
      changedEquationParts(
        distribution.equation,
        changedDistribution.equation,
      ),
    ).not.toEqual([]);

    expect(
      changedEquationParts(
        distribution.equation,
        { ...distribution.equation, solution: 99 },
      ),
    ).toEqual([]);

    const oneStep = createSeededProblem(42, 1);
    expect(
      changedEquationParts(
        oneStep.equation,
        oneStep.transferProblem.equation,
      ),
    ).toEqual(["expression"]);
  });

  it("builds one concise live-region update in reading order", () => {
    const announcement = tutorUpdateAnnouncement(tutorTurn);

    expect(announcement).toContain(
      "Guidance: The distributed constant changed value.",
    );
    expect(announcement).not.toContain("Keep both sides balanced.");
    expect(announcement.indexOf("Guidance:")).toBeLessThan(
      announcement.indexOf("Next:"),
    );
    expect(announcement).toContain("Next: What would you add to both sides?");
    expect(problemUpdateAnnouncement("Solve for x: 2(x + 1) = 8")).toBe(
      "New problem loaded. Solve for x: 2(x + 1) = 8",
    );
  });

  it("uses requested or stronger guidance instead of a repeated diagnosis", () => {
    expect(tutorGuidanceText(tutorTurn)).toBe(
      "The distributed constant changed value.",
    );
    expect(tutorGuidanceText(tutorTurn, true)).toBe(
      "Keep both sides balanced.",
    );
    expect(
      tutorGuidanceText({
        ...tutorTurn,
        intervention: "concept_cue",
        hintLevel: 2,
      }),
    ).toBe("Keep both sides balanced.");
    expect(tutorUpdateAnnouncement(tutorTurn, true)).toContain(
      "Guidance: Keep both sides balanced.",
    );
  });

  it("names every actual tutor response source distinctly", () => {
    expect(tutorSourceLabel("openai", "gpt-5.6")).toBe(
      "Answered by GPT-5.6",
    );
    expect(tutorSourceLabel("deterministic-safeguard", null)).toBe(
      "Deterministic safeguard",
    );
    expect(tutorSourceLabel("deterministic-demo", null)).toBe(
      "Demo safeguard used",
    );
    expect(tutorSourceLabel("deterministic-fallback", null)).toBe(
      "GPT unavailable · safeguard used",
    );

    expect(tutorSourceExplanation("openai")).toContain("generated by AI");
    expect(tutorSourceExplanation("deterministic-safeguard")).toContain(
      "Fixed application rules",
    );
    expect(tutorSourceExplanation("deterministic-demo")).toContain(
      "fixed demo rules",
    );
    expect(tutorSourceExplanation("deterministic-fallback")).toContain(
      "GPT was requested but unavailable",
    );
  });
});
