import { formatEquation } from "./problems";
import type { LinearEquationParameters, TutorTurn } from "./types";

export type TutorSource =
  | "openai"
  | "deterministic-demo"
  | "deterministic-fallback"
  | "deterministic-safeguard";

export type VisibleEquationPart =
  | "multiplier"
  | "offset"
  | "rightSide"
  | "expression";

export const HELP_REVEAL_DELAY_MS = 8_000;

export const GUIDANCE_REVEAL_ORDER = [
  "learner",
  "diagnosis",
  "feedback",
  "nextPrompt",
  "evidence",
] as const;

export type GuidanceRevealStep = (typeof GUIDANCE_REVEAL_ORDER)[number];

const GUIDANCE_REVEAL_DELAYS_MS: Record<GuidanceRevealStep, number> = {
  learner: 0,
  diagnosis: 100,
  feedback: 260,
  nextPrompt: 420,
  evidence: 560,
};

export function guidanceRevealDelayMs(step: GuidanceRevealStep) {
  return GUIDANCE_REVEAL_DELAYS_MS[step];
}

export function changedEquationParts(
  previous: LinearEquationParameters,
  next: LinearEquationParameters,
) {
  if (previous.form !== "distribution" || next.form !== "distribution") {
    return formatEquation(previous) === formatEquation(next)
      ? []
      : (["expression"] satisfies VisibleEquationPart[]);
  }

  return (["multiplier", "offset", "rightSide"] as const).filter(
    (part) => previous[part] !== next[part],
  );
}

export function problemUpdateAnnouncement(prompt: string) {
  return `New problem loaded. ${prompt}`;
}

export function tutorGuidanceText(
  turn: TutorTurn,
  guidanceRequested = false,
) {
  return turn.intervention === "socratic_question" && !guidanceRequested
    ? turn.diagnosis
    : turn.feedback;
}

export function tutorUpdateAnnouncement(
  turn: TutorTurn,
  guidanceRequested = false,
) {
  return [
    "Tutor response ready.",
    `Guidance: ${tutorGuidanceText(turn, guidanceRequested)}`,
    `Next: ${turn.nextPrompt}`,
  ].join(" ");
}

export function tutorSourceLabel(source: TutorSource, model: string | null) {
  switch (source) {
    case "openai":
      return `Answered by ${(model || "GPT-5.6").toUpperCase()}`;
    case "deterministic-safeguard":
      return "Deterministic safeguard";
    case "deterministic-fallback":
      return "GPT unavailable · safeguard used";
    case "deterministic-demo":
      return "Demo safeguard used";
  }
}

export function tutorSourceExplanation(source: TutorSource) {
  switch (source) {
    case "openai":
      return "This guidance was generated by AI and may contain errors.";
    case "deterministic-safeguard":
      return "Fixed application rules handled this explicit help request instead of generative AI.";
    case "deterministic-fallback":
      return "GPT was requested but unavailable, so fixed application rules produced this response.";
    case "deterministic-demo":
      return "Live GPT did not generate this response; fixed demo rules produced it.";
  }
}
